[background]
path = "/etc/greetd/backgrounds/1-totoro.png"
fit = "Cover"

[GTK]
application_prefer_dark_theme = true
cursor_theme_name = "Adwaita"
font_name = "Cantarell 12"
icon_theme_name = "Adwaita"
theme_name = "Adwaita"

[commands]
reboot = ["systemctl", "reboot"]
poweroff = ["systemctl", "poweroff"]

[appearance]
greeting_msg = "Welcome back"

[widget.clock]
format = "%a %d %b  %H:%M"
resolution = "500ms"
label_width = 180