env = GTK_USE_PORTAL,0
env = GDK_DEBUG,no-portals

input {
    kb_layout = us

    touchpad {
        tap-to-click = true
        tap-and-drag = true
        drag_lock = 0
        natural_scroll = false
    }
}

exec-once = regreet; hyprctl dispatch exit

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    disable_hyprland_guiutils_check = true
}